deepl: &deepl
  command: |
    xdotool mouseup 1
    text=$(xsel -p | ruby -r 'erb' -ne 'puts ERB::Util.url_encode $_')
    url="https://www.deepl.com/translator#en/ja/$text"
    google-chrome  --incognito --app=deepl.com "$url"
  interval: 5

miraitranslate: &miraitranslate
  command: |
    xdotool mouseup 1
    text=$(xsel -p | ruby -r 'erb' -ne 'puts ERB::Util.url_encode $_')
    url="https://miraitranslate.com/trial/#en/ja/$text"
    google-chrome  --incognito --app=deepl.com "$url"
  interval: 5

swipe_drag: &swipe_drag
  begin:
    command: xdotool mousedown 1
  update:
    command: xdotool mousemove_relative -- $move_x, $move_y
    # command: xdotool mousemove_relative -- $unaccelerated_x, $unaccelerated_y
    interval: 0.01
    accel: 3
  end:
    command: xdotool mouseup 1
    keypress:
      LEFTSHIFT+LEFTCTRL:
        <<: *deepl
      LEFTCTRL+LEFTSHIFT:
        <<: *deepl
      LEFTSHIFT+LEFTALT:
        <<: *miraitranslate
      LEFTALT+LEFTSHIFT:
        <<: *miraitranslate

swipe_alt+tab: &swipe_alt_tab
  begin:
    command: xdotool keydown Alt
  right:
    update:
      # TODO: update効いてない？
      command: xdotool key Tab
      interval: 5
  left:
    update:
      command: xdotool key Shift+Tab
      interval: 5
  end:
    command: xdotool keyup Alt

thumbsense:
  J:
    pressed:
      sendbutton: 
        pressed: LEFT
    released:
      sendbutton:
        released: LEFT
      # TODO: press/releaseと同期させる

  # K:
  #   pressed:
  #     sendbutton: RIGHT
  # F:
  #   sendbutton: LEFT
  # D:
  #   sendbutton: RIGHT
  # RIGHTALT:
  #   sendbutton: LEFT
  # RIGHTCTRL:
  #   sendbutton: RIGHT

swipe:
  3:
    # <<: *swipe_drag
    # <<: *swipe_alt_tab
    left:
      keypress:
        LEFTMETA:
          sendkey: LEFTMETA+LEFT # move window to next workspace
    right:
      keypress:
        LEFTMETA:
          sendkey: LEFTMETA+RIGHT # move window to next workspace
    up:
      keypress:
        LEFTMETA:
          sendkey: LEFTMETA+UP # move window to next workspace
    down:
      keypress:
        LEFTMETA:
          sendkey: LEFTMETA+DOWN # move window to next workspace

  4:
    left:
      sendkey: LEFTCTRL+LEFTALT+RIGHT
      keypress:
        LEFTSHIFT:
          sendkey: LEFTSHIFT+LEFTMETA+PAGEDOWN # move window to next workspace
    right:
      sendkey: LEFTCTRL+LEFTALT+LEFT
      keypress:
        LEFTSHIFT:
          sendkey: LEFTSHIFT+LEFTMETA+PAGEUP # move window to prev workspace

    # In Gnome-shell, swipe-up or swipe-down triggers built-in swipe gestures(toggle overview) while pressing modifier keys
    # up:
    #   keypress:
    #     LEFTSHIFT:
    #       sendkey: LEFTSHIFT+LEFTMETA+down # move window to lower display
    # down:
    #   keypress:
    #     LEFTSHIFT:
    #       sendkey: LEFTSHIFT+LEFTMETA+UP # move window to upper display

pinch:
  2:
    # in:
    #   update:
    #     command: 'xdotool key ctrl+equal'
    #     interval: 3.0
    # out:
    #   update:
    #     command: 'xdotool key ctrl+minus'
    #     interval: 3.0
    begin:
      command: xdotool keydown ctrl
    end:
      command: xdotool keyup ctrl
    in:
      update:
        command: xdotool click 4 # Zoom in
    out:
      update:
        command: xdotool click 5 # Zoom out

rotate:
  3:
    clockwise:
      update:
        sendkey: VOLUMEUP
        keypress:
          LEFTSHIFT:
            sendkey: LEFTSHIFT+VOLUMEUP
          LEFTALT:
            sendkey: BRIGHTNESSUP
    counterclockwise:
      update:
        sendkey: VOLUMEDOWN
        keypress:
          LEFTALT:
            sendkey: BRIGHTNESSDOWN
          LEFTSHIFT:
            sendkey: LEFTSHIFT+VOLUMEDOWN

hold:
  3:
    sendkey: "LEFTALT+F7" # move window
    keypress:
      LEFTSHIFT:
        sendkey: "LEFTALT+F8" # resize window
  4:
    sendkey: "MUTE"

plugin:
  inputs:
    libinput_command_input:
      show-keycodes: true
      enable-tap: true
      enable-dwt: true
      verbose: true
      libinput-list-devices: /home/iberianpig/.ghq/gitlab.freedesktop.org/libinput/libinput/builddir/1.19.1/libinput-list-devices
      libinput-debug-events: /home/iberianpig/.ghq/gitlab.freedesktop.org/libinput/libinput/builddir/1.19.1/libinput-debug-events
      # libinput-list-devices: /home/iberianpig/.ghq/gitlab.freedesktop.org/libinput/libinput/builddir/1.19.0/libinput-list-devices
      # libinput-debug-events: /home/iberianpig/.ghq/gitlab.freedesktop.org/libinput/libinput/builddir/1.19.0/libinput-debug-events
      # libinput-list-devices: /home/iberianpig/.ghq/gitlab.freedesktop.org/libinput/libinput/builddir/1.17.0/libinput-list-devices
      # libinput-debug-events: /home/iberianpig/.ghq/gitlab.freedesktop.org/libinput/libinput/builddir/1.17.0/libinput-debug-events
      # libinput-list-devices: /home/iberianpig/.ghq/gitlab.freedesktop.org/libinput/libinput/builddir/1.16.5/libinput-list-devices
      # libinput-debug-events: /home/iberianpig/.ghq/gitlab.freedesktop.org/libinput/libinput/builddir/1.16.5/libinput-debug-events

---
context:
  application: Google-chrome
  # default: { applicaton: Google-chrome }

swipe:
  3:
    left:
      # sendevent: touchscreen
      sendkey: "LEFTALT+RIGHT"
    right:
      sendkey: "LEFTALT+LEFT"
    up:
      sendkey: "LEFTCTRL+T"
      keypress:
        LEFTSHIFT:
          sendkey: "LEFTSHIFT+LEFTCTRL+T"
    down:
      sendkey: "LEFTCTRL+Q"
---
context:
  application: Chromium

swipe:
  3:
    left:
      # sendevent: touchscreen
      sendkey: "LEFTALT+RIGHT"
    right:
      sendkey: "LEFTALT+LEFT"
    up:
      sendkey: "LEFTCTRL+T"
      keypress:
        LEFTSHIFT:
          sendkey: "LEFTSHIFT+LEFTCTRL+T"
    down:
      sendkey: "LEFTCTRL+Q"
---
context:
  application: Firefox

# swipe:
#   3:
#     left:
#       sendkey: 'LEFTALT+RIGHT'
#     right:
#       sendkey: 'LEFTALT+LEFT'
#     up:
#       sendkey: 'LEFTCTRL+T'
#     down:
#       sendkey: 'LEFTCTRL+Q'
swipe:
  3:
    begin:
      command: xdotool keydown Ctrl
    right:
      sendkey: "LEFTCTRL+PAGEDOWN"
      keypress:
        LEFTSHIFT:
          sendkey: "LEFTALT+LEFT"
      update:
        command: xdotool key Tab
        interval: 3
    left:
      sendkey: "LEFTCTRL+PAGEUP"
      keypress:
        LEFTSHIFT:
          sendkey: "LEFTALT+RIGHT"
      update:
        command: xdotool key Shift+Tab
        interval: 3
    end:
      command: xdotool keyup Ctrl
---
context:
  application:
    # Gnome-terminal # X11
    gnome-terminal-server # wayland

swipe:
  3:
    up:
      sendkey: "LEFTSHIFT+LEFTCTRL+T"
    down:
      sendkey: "LEFTSHIFT+LEFTCTRL+W"
# thumbsense:
#   L:
#     sendkey: LEFTALT+RIGHT # tmux next window
#   H:
#     sendkey: LEFTALT+LEFT # tmux next window

---
context:
  application: Slack

swipe:
  3:
    left:
      sendkey: "LEFTALT+RIGHT"
    right:
      sendkey: "LEFTALT+LEFT"
    up:
      sendkey: "LEFTALT+DOWN"
    down:
      sendkey: "LEFTALT+UP"
