swipe:
  3:
    left:
      command: 'xdotool key ctrl+alt+Right'
    right:
      command: 'xdotool key ctrl+alt+Left'
    up:
      command: 'xdotool key super+s'
    #down:
    #  command: 'xdotool key super+s'
  4:
    left:
      command: 'xdotool key super+alt+Right'
    right:
      command: 'xdotool key super+alt+Left'
    #up:
      #command: 'xdotool key super+a'
    #down:
      #command: 'xdotool key super+s'

pinch:
  in:
    command: 'xdotool key ctrl+plus'
  out:
    command: 'xdotool key ctrl+minus'

threshold:
  swipe: 1
  pinch: 0.5

interval:
  swipe: 1
  pinch: 0.5
