deepl: &deepl
  command: |
    xdotool mouseup 1
    text=$(xsel -p | ruby -r 'erb' -ne 'puts ERB::Util.url_encode $_')
    url="https://www.deepl.com/translator#en/ja/$text"
    google-chrome  --incognito --app=deepl.com "$url"
  interval: 5

miraitranslate: &miraitranslate
  command: |
    xdotool mouseup 1
    text=$(xsel -p | ruby -r 'erb' -ne 'puts ERB::Util.url_encode $_')
    url="https://miraitranslate.com/trial/#en/ja/$text"
    google-chrome  --incognito --app=deepl.com "$url"
  interval: 5

swipe:
  drag: &drag
    begin:
      command: xdotool mousedown 1
    update:
      command: xdotool mousemove_relative -- $move_x, $move_y
      # command: xdotool mousemove_relative -- $unaccelerated_x, $unaccelerated_y
      interval: 0.01
      accel: 3
    end:
      command: xdotool mouseup 1
      keypress:
        LEFTSHIFT+LEFTCTRL:
          <<: *deepl
        LEFTCTRL+LEFTSHIFT:
          <<: *deepl
        LEFTSHIFT+LEFTALT:
          <<: *miraitranslate
        LEFTALT+LEFTSHIFT:
          <<: *miraitranslate

  alt+tab: &alt_tab
    begin:
      command: xdotool keydown Alt
    right:
      update:
        command: xdotool key Tab
        interval: 5
    left:
      update:
        command: xdotool key Shift+Tab
        interval: 5
    end:
      command: xdotool keyup Alt
  3:
    <<: *drag
    # <<: *alt_tab
  4:
    left:
      sendkey: LEFTMETA+PAGEDOWN # move to next workspace
      keypress:
        LEFTSHIFT:
          sendkey: LEFTSHIFT+LEFTMETA+PAGEDOWN # move window to next workspace
    right:
      sendkey: LEFTMETA+PAGEUP # move to prev workspace
      keypress:
        LEFTSHIFT:
          sendkey: LEFTSHIFT+LEFTMETA+PAGEUP # move window to prev workspace
    up:
      sendkey: LEFTMETA+S
    down:
      sendkey: LEFTMETA+S

pinch:
  2:
    # in:
    #   update:
    #     command: 'xdotool key ctrl+equal'
    #     interval: 3.0
    # out:
    #   update:
    #     command: 'xdotool key ctrl+minus'
    #     interval: 3.0
    begin:
      command: xdotool keydown ctrl
    end:
      command: xdotool keyup ctrl
    in:
      update:
        command: xdotool click 4 # Zoom in
    out:
      update:
        command: xdotool click 5 # Zoom out

rotate:
  3:
    clockwise:
      update:
        sendkey: VOLUMEUP
        keypress:
          LEFTSHIFT:
            sendkey: LEFTSHIFT+VOLUMEUP
          LEFTALT:
            sendkey: BRIGHTNESSUP
    counterclockwise:
      update:
        sendkey: VOLUMEDOWN
        keypress:
          LEFTALT:
            sendkey: BRIGHTNESSDOWN
          LEFTSHIFT:
            sendkey: LEFTSHIFT+VOLUMEDOWN

hold:
  3:
    sendkey: "LEFTALT+F7" # move window
    keypress:
      LEFTSHIFT:
        sendkey: "LEFTALT+F8" # resize window
  4:
    sendkey: "MUTE"

typing: # disable while typing
  # interval: 0.5
  # command: |
  #   ruby <<RUBY
  #     require 'revdev'
  #     require 'fileutils'
  # 
  #     filepath="/tmp/typing_command_break"
  #     until_dir = "/tmp/typing_break/#{Process.ppid}"
  #     evdev = Revdev::EventDevice.new("/dev/input/event10")
  # 
  #     if !Dir.exist?(until_dir)
  #       begin
  #         evdev.grab
  #       rescue => ex
  #         puts "====================="
  #         puts ex.full_message
  #         puts "====================="
  #         return
  #       end
  #       FileUtils.mkdir_p(until_dir)
  #     else
  #       return
  #     end
  # 
  #     sleep 0.4
  # 
  #     begin
  #       evdev.ungrab
  #     rescue => ex
  #       puts "====================="
  #       puts ex.full_message
  #       puts "====================="
  #     end
  #     Dir.rmdir(until_dir)
  #   RUBY

  # interval: 0.6
  # command: | # X11
  #   touchpad_id=$(xinput | grep Touchpad | grep -oE "id=[0-9]*" | cut -d"=" -f 2)
  #   xinput set-prop $touchpad_id "libinput Tapping Enabled" 0
  #   file=/tmp/typing_command_break
  #   touch "$file"
  #   sleep 0.6
  #   [ `find "$file" -mmin +0.01` ] && \
  #     xinput set-prop $touchpad_id "libinput Tapping Enabled" 1
  command: | # Gnome Wayland
    gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click false

    file=/tmp/typing_command_break
    touch "$file"
    sleep 0.6

    [ `find "$file" -mmin +0.01` ] && gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click true
  


plugin:
  inputs:
    libinput_command_input:
      show-keycodes: true
      enable-tap: true
      enable-dwt: true
      verbose: true
      libinput-list-devices: /home/iberianpig/.ghq/gitlab.freedesktop.org/libinput/libinput/builddir/1.19.1/libinput-list-devices
      libinput-debug-events: /home/iberianpig/.ghq/gitlab.freedesktop.org/libinput/libinput/builddir/1.19.1/libinput-debug-events
      # libinput-list-devices: /home/iberianpig/.ghq/gitlab.freedesktop.org/libinput/libinput/builddir/1.19.0/libinput-list-devices
      # libinput-debug-events: /home/iberianpig/.ghq/gitlab.freedesktop.org/libinput/libinput/builddir/1.19.0/libinput-debug-events
      # libinput-list-devices: /home/iberianpig/.ghq/gitlab.freedesktop.org/libinput/libinput/builddir/1.17.0/libinput-list-devices
      # libinput-debug-events: /home/iberianpig/.ghq/gitlab.freedesktop.org/libinput/libinput/builddir/1.17.0/libinput-debug-events
      # libinput-list-devices: /home/iberianpig/.ghq/gitlab.freedesktop.org/libinput/libinput/builddir/1.16.5/libinput-list-devices
      # libinput-debug-events: /home/iberianpig/.ghq/gitlab.freedesktop.org/libinput/libinput/builddir/1.16.5/libinput-debug-events
---
context:
  application: Google-chrome

swipe:
  3:
    left:
      sendkey: 'LEFTALT+RIGHT'
    right:
      sendkey: 'LEFTALT+LEFT'
    up:
      sendkey: 'LEFTCTRL+T'
      keypress:
        LEFTSHIFT:
          sendkey: 'LEFTSHIFT+LEFTCTRL+T'
    down:
      sendkey: 'LEFTCTRL+Q'
---
context:
  application: Firefox

# swipe:
#   3:
#     left:
#       sendkey: 'LEFTALT+RIGHT'
#     right:
#       sendkey: 'LEFTALT+LEFT'
#     up:
#       sendkey: 'LEFTCTRL+T'
#     down:
#       sendkey: 'LEFTCTRL+Q'
swipe:
  3: 
    begin:
      command: xdotool keydown Ctrl
    right:
      sendkey: 'LEFTCTRL+PAGEDOWN'
      keypress:
        LEFTSHIFT:
          sendkey: 'LEFTALT+LEFT'
      update:
        command: xdotool key Tab
        interval: 3
    left:
      sendkey: 'LEFTCTRL+PAGEUP'
      keypress:
        LEFTSHIFT:
          sendkey: 'LEFTALT+RIGHT'
      update:
        command: xdotool key Shift+Tab
        interval: 3
    end:
      command: xdotool keyup Ctrl
---
context:
  application: 
    Gnome-terminal # X11
    # gnome-terminal-server # wayland


swipe:
  3:
    up:
      sendkey: 'LEFTSHIFT+LEFTCTRL+T'
    down:
      sendkey: 'LEFTSHIFT+LEFTCTRL+W'
    right:
      sendkey: 'LEFTCTRL+PAGEUP'
    left:
      sendkey: 'LEFTCTRL+PAGEDOWN'

# pinch:
#   2:
#     in:
#       update:
#         sendkey: 'LEFTCTRL+EQUAL'
#         interval: 3
#     out:
#       update:
#         sendkey: 'LEFTCTRL+MINUS'
#         interval: 3

---
context:
  application: Slack

swipe:
  3:
    left:
      sendkey: 'LEFTALT+RIGHT'
    right:
      sendkey: 'LEFTALT+LEFT'
    up:
      sendkey: "LEFTALT+DOWN"
    down:
      sendkey: "LEFTALT+UP"
