swipe:
  3:
    left:
      command: 'xdotool key alt+Right'
      # command: 'xdotool key alt+Escape'
      # command: 'xdotool keydown alt && sleep .1 && xdotool key Tab  && xdotool keyup alt'
    right:
      command: 'xdotool key alt+Left'
    up:
      command: 'xdotool key alt+t'
    down:
      command: 'xdotool key alt+w'
  4:
    left:
      # shortcut: 'super+Right'
      command: 'sh ~/Dropbox/tool/linux/script/desktop_switcher.sh 1'
    right:
      # shortcut: 'super+Left'
      command: 'sh ~/Dropbox/tool/linux/script/desktop_switcher.sh -1' 
    up:
      command: 'xdotool key super+s'
    down:
      command: 'xdotool key super+a'
    key_leftmeta:
      up:
        command: 'xdotool key XF86MonBrightnessUp'
      down:
        command: 'xdotool key XF86MonBrightnessDown'
pinch:
  2:
    in:
      # command: 'xdotool key ctrl+equal'
      command: 'xdotool keydown ctrl click 4 keyup ctrl'
    out:
      command: 'xdotool keydown ctrl click 5 keyup ctrl'
  4:
    in:
      command: 'xdotool key super+a'
    out:
      command: 'xdotool key super+s'

rotate:
  3:
    clockwise:
      command: 'xdotool key XF86MonBrightnessUp'
    counterclockwise:
      command: 'xdotool key XF86MonBrightnessDown'

tap:
  1:
    command: 'xdotool click 1'
  2:
    command: 'xdotool click 3'
  3:
    command: 'xdotool key super+space'

plugin: 
  inputs:
    libinput_command_input: # options for lib/plugin/inputs/libinput_command_input
      enable-tap: true
      device: /dev/input/event16

# threshold:
#   rotate: 0.1
# #   swipe: 0.3
# #   pinch: 0.3
# #
# interval:
#   rotate: 0.5
# #   swipe: 1
# #   pinch: 0.3

local_plugin_paths: 
  - "/home/iberianpig/.ghq/github.com/iberianpig/fusuma-plugin-tap/lib/fusuma/plugin/tap.rb"

window:
  - class: '/google-chrome/'
    swipe: 
      3:
        left:
          command: 'xdotool alt+right'
        right:
          command: 'xdotool alt+left'
        up: 
          command: 'xdotool ctrl+t'
          key:
            - value: 'Up'
              command: 'xdotool ctrl+shift+t'

  - class: '/hoge/'
  - class: '/hoge/'
