swipe:
  3:
    left:
      command: 'xdotool key alt+Right'
    right:
      command: 'xdotool key alt+Left'
    up:
      command: 'xdotool key alt+t'
    down:
      command: 'xdotool key alt+w'
  4:
    left:
      command: 'xdotool key super'  # gnome-shell
    right:
      command: 'xdotool key super+a' # gnome-shell
    up:
      command: 'sh ~/Dropbox/tool/linux/script/desktop_switcher.sh 1' # gnome-shell
    down:
      command: 'sh ~/Dropbox/tool/linux/script/desktop_switcher.sh -1' # gnome-shell
pinch:
  2:
    in:
      command: 'xdotool key ctrl+equal'
    out:
      command: 'xdotool key ctrl+minus'
  4:
    in:
      command: 'xdotool key super+a'
    out:
      command: 'xdotool key super+s'

threshold:
  swipe: 0.1
  pinch: 0.5

interval:
  swipe: 0.5
  pinch: 0.3
