application:
  global:
    swipe:
      3:
        left:
          # command: for i in {1..5} ; do sh -c 'fusuma-sendkey VOLUMEDOWN &' ; done
          sendkey: "LEFTALT+RIGHT"
          # command: 'xdotool key alt+Right'
          # command: "xte 'keydown Alt_L' 'keydown Right' 'keyup Right' 'keyup Alt_L'"
          # command: 'xdotool key alt+Escape'
          # command: 'xdotool keydown alt && sleep .1 && xdotool key Tab  && xdotool keyup alt'
          # command: ~/.ghq/github.com/iberianpig/fusuma-plugin-wmctrl/bin/cycle.sh 1
        right:
          # command: "fusuma-sendkey VOLUMEDOWN && fusuma-sendkey VOLUMEDOWN && fusuma-sendkey VOLUMEDOWN"
          sendkey: "LEFTALT+LEFT"
          # command: 'xdotool key alt+Left'
          # command: "xte 'keydown Alt_L' 'keydown Left' 'keyup Left' 'keyup Alt_L'"
          # command: ~/.ghq/github.com/iberianpig/fusuma-plugin-wmctrl/bin/cycle.sh -1
        up:
          sendkey: "LEFTCTRL+T"
          keypress:
            LEFTSHIFT:
              sendkey: "LEFTCTRL+LEFTSHIFT+T"
        down:
          sendkey: "LEFTALT+W"
      4:
        left:
          # shortcut: 'super+Right'
          # command: 'xdotool key super+Right'
          sendkey: 'LEFTMETA+RIGHT'
          # workspace: "next"
          keypress:
            LEFTSHIFT:
              # window: "next"
              sendkey: 'LEFTALT+LEFTMETA+RIGHT'
              # command: 'xdotool key --clearmodifiers super+alt+Right'
            LEFTMETA:
              # command: "xdotool key --clearmodifiers super+ctrl+Left"
              sendkey: "LEFTMETA+LEFTCTRL+LEFT"
            LEFTCTRL:
              # command: 'xdotool key --clearmodifiers XF86MonBrightnessDown'
              sendkey: BRIGHTNESSDOWN
            LEFTALT:
              sendkey: VOLUMEDOWN
        right:
          sendkey: 'LEFTMETA+LEFT'
          # shortcut: 'super+Left'
          # command: 'xdotool key super+Left'
          # workspace: "prev"
          keypress:
            LEFTSHIFT:
              # window: "prev"
              sendkey: 'LEFTALT+LEFTMETA+LEFT'
              # command: 'xdotool key --clearmodifiers super+alt+Left'
              # sendkey: 'LEFTMETA+LEFTALT+RIGHT'
            LEFTMETA:
              # command: "xdotool key --clearmodifiers super+ctrl+Right"
              sendkey: "LEFTMETA+LEFTCTRL+RIGHT"
            LEFTCTRL:
              sendkey: BRIGHTNESSUP
              # command: 'xdotool key --clearmodifiers XF86MonBrightnessUp'
            LEFTALT:
              sendkey: VOLUMEUP
        up:
          sendkey: "LEFTMETA+S"
          keypress:
            LEFTMETA:
              window:
                # fullscreen: 'add'
                maximized: "toggle"

          # window: "maximized"
            # fullscreen: 'add'
          # command: "xdotool key super+s"
          # sendkey: "LEFTMETA+S"
          # keypress:
          #   LEFTSHIFT:
          #   # command: 'xdotool key --clearmodifiers XF86MonBrightnessUp'
          #   LEFTALT:
          #     # command: "xdotool key --clearmodifiers XF86AudioRaiseVolume"
          #     sendkey: VOLUMEUP
          #   LEFTMETA:
          #     # command: 'xdotool key --clearmodifiers super+Up'
          #     window:
          #       # fullscreen: 'add'
          #       maximized: "toggle"
        down:
          sendkey: "LEFTMETA+a"
          keypress:
            LEFTMETA:
              # command: 'xdotool key --clearmodifiers super+Up'
              # window:
              # fullscreen: 'remove'
              window: "close"

    pinch:
      in:
        command: "xdotool keydown ctrl click 4 keyup ctrl"
        # sendkey: LEFTCTRL+EQUAL
        keypress:
          LEFTMETA:
            sendkey: LEFTMETA+EQUAL
            # threshold: 0.1
      out:
        command: "xdotool keydown ctrl click 5 keyup ctrl"
        # sendkey: LEFTCTRL+MINUS
        keypress:
          LEFTMETA:
            sendkey: LEFTMETA+MINUS
            # threshold: 10.1
      # 4:
      #   in:
      #     command: "xdotool key super+a"
      #   out:
      #     command: "xdotool key super+s"

    rotate:
      3:
        clockwise:
          # command: "xdotool key XF86MonBrightnessUp"
          sendkey: "BRIGHTNESSUP"
        counterclockwise:
          sendkey: "BRIGHTNESSDOWN"

    tap:
      # 1:
      #   command: 'notify-send tap 1'
      # 2:
      #   command: 'notify-send tap 2'
      # 3:
      #   command: 'notify-send tap 3'
      4:
        command: 'notify-send tap 4'

    # hold:
    #   # 1:
    #   #   command: 'notify-send hold 1'
    #   # 2:
    #   #   command: 'notify-send hold 2'
    #   3:
    #     # command: "xdotool click --repeat 2 1 && goldendict $(xsel -p)"
    #     # command: test -n "$(xsel -p)" && xdg-open https://www.deepl.com/translator#auto/auto/"$(xsel -p)"
    #     # command: test -n "$(xsel -p)" && pkill pennywise ; echo $(xsel -p) | ruby -ne 'p URI.encode $_' | xargs -I{} pennywise --args --url https://www.deepl.com/translator#auto/auto/{}
    #     command: test -n "$(xsel -p)" && echo $(xsel -p) | ruby -ne 'p URI.encode $_' | xargs -I{} google-chrome --new-window --app=https://www.deepl.com/translator#auto/auto/{}
    #   4:
    #     # command: 'notify-send hold 4'
    #     sendkey: "LEFTALT+F7"

    hold:
      3:
        command: test -n "$(xsel -p)" && echo $(xsel -p) | ruby -ne 'p URI.encode $_' | xargs -I{} google-chrome --new-window --app=https://www.deepl.com/translator#auto/auto/{}
      4: &default_hold_4
        sendkey: "LEFTALT+F7" # move window
        keypress:
          LEFTSHIFT:
            sendkey: "LEFTALT+F8" # resize window

  Terminal: &Terminal
    swipe:
      3: 
        up:
          # sendkey: "LEFTMETA+LEFTSHIFT+F"
          window: {fullscreen: 'add'}
          keypress: 
            LEFTSHIFT:
              sendkey: "LEFTMETA+LEFTSHIFT+F"
        down:
          window: {fullscreen: 'remove'}
    hold:
      3:
        command: 'notify-send hold 3'

  Alacritty:
    <<: *Terminal

  Files:
    swipe:
      3: 
        down:
          sendkey: "LEFTCTRL+W"

  Google Calendar:
    swipe:
      3: 
        down:
          sendkey: "LEFTCTRL+W"

threshold:
  rotate: 1
  swipe: 1
  pinch: 1

interval:
  rotate: 1
  swipe: 1
  pinch: 1


plugin:
  inputs:
    libinput_command_input: # options for lib/plugin/inputs/libinput_command_input
      enable-tap: true
      enable-dwt: true
      show-keycodes: true
      verbose: true
      libinput-list-devices: /home/iberianpig/.ghq/gitlab.freedesktop.org/libinput/libinput/builddir/libinput-list-devices
      libinput-debug-events: /home/iberianpig/.ghq/gitlab.freedesktop.org/libinput/libinput/builddir/libinput-debug-events
  filters:
    libinput_device_filter:
      keep_device_names:
        # - "DLL075B:01 06CB:76AF Touchpad"
        # - Logitech Rechargeable Touchpad T650
        # - hogehoge
  buffers:
    gesture_buffer:
      # seconds_to_keep: 0.01
  # executors:
  #   sendkey_executor:
  #     device_name: 
# 
# application:
#   Google chrome:
#     swipe:
#       3:
#         left:
#           command: "xdotool alt+right"
#         right:
#           command: "xdotool alt+left"
#         up:
#           command: "xdotool ctrl+t"
#           keypress:
#             - code: "Up"
#               command: "xdotool ctrl+shift+t"
# 
# scroll:
#   4:
#     up:
#       command:
#         LEFTSHIFT:
#           command: "xdotool key --clearmodifiers XF86MonBrightnessUp"
#     down:
#       command:
#         LEFTSHIFT:
#           command: "xdotool key --clearmodifiers XF86MonBrightnessDown"
# 
