swipe:
  3:
    left:
      command: 'xdotool key alt+Right'
    right:
      command: 'xdotool key alt+Left'
    up:
      command: 'xdotool key alt+t'
    down:
      command: 'xdotool key alt+w'
  4:
    left:
      command: 'xdotool key super+Right'
    right:
      command: 'xdotool key super+Left'
    up:
      command: 'xdotool key super+s'
    down:
      command: 'xdotool key super+a'

pinch:
  2:
    in:
      command: 'xdotool keydown ctrl click 4 keyup ctrl'
    out:
      command: 'xdotool keydown ctrl click 5 keyup ctrl'
  4:
    in:
      command: 'xdotool key super+a'
    out:
      command: 'xdotool key super+s'

rotate:
  3:
    clockwise:
      command: 'xdotool key XF86MonBrightnessUp'
    counterclockwise:
      command: 'xdotool key XF86MonBrightnessDown'

# threshold:
#   rotate: 0.1
#   swipe: 1
#   pinch: 0.3
#
# interval:
#   rotate: 0.5
#   swipe: 0.5
#   pinch: 0.3


# local_plugin_paths: 
#   - "/home/iberianpig/.ghq/github.com/iberianpig/fusuma-plugin-tap/lib/fusuma/plugin/tap.rb"
