swipe:
  3:
    left:
      command: 'xdotool key alt+Right'
      # command: 'xdotool key alt+Escape'
      # command: 'xdotool keydown alt && sleep .1 && xdotool key Tab  && xdotool keyup alt'
    right:
      command: 'xdotool key alt+Left'
    up:
      command: 'xdotool key alt+t'
    down:
      command: 'xdotool key alt+w'
  4:
    left:
      shortcut: 'super+Right'
      # command: 'sh ~/Dropbox/tool/linux/script/desktop_switcher.sh 1'
    right:
      shortcut: 'super+Left'
      # command: 'sh ~/Dropbox/tool/linux/script/desktop_switcher.sh -1' 
    up:
      command: 'xdotool key super+s'
    down:
      command: 'xdotool key super+a'
pinch:
  2:
    in:
      command: 'xdotool key ctrl+equal'
      threshold: 0.5
    out:
      command: 'xdotool key ctrl+minus'
      threshold: 0.5
  4:
    in:
      command: 'xdotool key super+a'
    out:
      command: 'xdotool key super+s'

rotate:
  3:
    clockwise:
      command: 'xdotool key XF86MonBrightnessUp'
    counterclockwise:
      command: 'xdotool key XF86MonBrightnessDown'

threshold:
  swipe: 0.3
  pinch: 0.5

interval:
  swipe: 1
  pinch: 0.3
