swipe:
  3:
    left:
      shortcut: 'alt+Right'
    right:
      shortcut: 'alt+Left'
    up:
      shortcut: 'alt+t'
    down:
      shortcut: 'alt+w'
  4:
    left:
      shortcut: 'super+Right'
    right:
      shortcut: 'super+Left'
    up:
      shortcut: 'super+a'
    down:
      shortcut: 'super+s'
pinch:
  in:
    shortcut: 'ctrl+plus'
  out:
    shortcut: 'ctrl+minus'

threshold:
  swipe: 0.1
  pinch: 0.8

interval:
  swipe: 0.5
  pinch: 0.3
