application:
  global:
    swipe:
      4:
        up:
          sendkey: 'LEFTCTRL+LEFTALT+DOWN'
          keypress:
            LEFTSHIFT:
              sendkey: 'LEFTSHIFT+LEFTCTRL+LEFTALT+DOWN'
        down:
          sendkey: 'LEFTCTRL+LEFTALT+UP'
          LEFTSHIFT:
            sendkey: 'LEFTSHIFT+LEFTCTRL+LEFTALT+UP'
        left:
          command: "dbus-send --session --type=method_call --dest=org.gnome.Shell /org/gnome/Shell org.gnome.Shell.Eval string:'if (Main.overview.visible && Main.overview.viewSelector._showAppsButton.checked) { Main.overview.hide();Main.overview.viewSelector._showAppsButton.checked=false;} else {Main.overview.show()}'"
          threshold: 1
          interval: 1
        right:
          command: "dbus-send --session --type=method_call --dest=org.gnome.Shell /org/gnome/Shell org.gnome.Shell.Eval string:'if (Main.overview.visible && !Main.overview.viewSelector._showAppsButton.checked) {Main.overview.hide()} else { Main.overview.viewSelector._showAppsButton.checked = true;Main.overview.show();}'"
          threshold: 1
          interval: 1

      3:
        left:
          sendkey: 'LEFTALT+RIGHT'
          keypress:
            LEFTMETA:
              sendkey: 'LEFTMETA+LEFT'
        right:
          sendkey: 'LEFTALT+LEFT'
          keypress:
            LEFTMETA:
              sendkey: 'LEFTMETA+RIGHT'
        up:
          sendkey: 'LEFTCTRL+T'
          keypress:
            LEFTMETA:
              sendkey: 'RIGHTMETA+UP'
        down:
          sendkey: 'LEFTCTRL+W'
          keypress:
            LEFTMETA:
              sendkey: 'RIGHTMETA+DOWN'
    pinch:
      2:
        in:
          sendkey: 'LEFTCTRL+EQUAL'
          threshold: 0.1
        out:
          sendkey: 'LEFTCTRL+MINUS'
          threshold: 0.1
      4:
        in:
          command: "dbus-send --session --type=method_call --dest=org.gnome.Shell /org/gnome/Shell org.gnome.Shell.Eval string:'if (Main.overview.visible && Main.overview.viewSelector._showAppsButton.checked) { Main.overview.hide();Main.overview.viewSelector._showAppsButton.checked=false;} else {Main.overview.show()}'"
          threshold: 1
          interval: 2
        out:
          command: "dbus-send --session --type=method_call --dest=org.gnome.Shell /org/gnome/Shell org.gnome.Shell.Eval string:'if (Main.overview.visible && !Main.overview.viewSelector._showAppsButton.checked) {Main.overview.hide()} else { Main.overview.viewSelector._showAppsButton.checked = true;Main.overview.show();}'"
          threshold: 1
          interval: 2

    hold:
      3:
        sendkey: "LEFTALT+F7" # move window
        keypress:
          LEFTSHIFT:
            sendkey: "LEFTALT+F8" # resize window

  Google-chrome:
    swipe: { 3: {down: { sendkey: 'LEFTCTRL+Q' } } }


plugin:
  inputs:
    libinput_command_input:
      show-keycodes: true
      enable-tap: true
      verbose: true
