- hosts: 127.0.0.1
  connection: local
  user: iberianpig
  tasks:
    - name: get upstream codename
      shell: lsb_release -usc
      register: upstream

    - debug: var=upstream.stdout  # bionic

    - name: add Docker CE apt gpg
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
      become: true
      args:
        warn: no

    - name: add Docker CE apt repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ upstream.stdout  }} stable
        state: present
      become: true

    - name: add playonlinux apt gpg
      shell: curl -fsSL http://deb.playonlinux.com/public.gpg | apt-key add -
      become: true
      args:
        warn: no

    - name: add playonlinux apt repository
      apt_repository:
        repo: deb http://deb.playonlinux.com/ {{ upstream.stdout }} main
        state: present
      become: true

    - name: add gyazo apt repository
      shell: which gyazo || curl -s https://packagecloud.io/install/repositories/gyazo/gyazo-for-linux/script.deb.sh | os=ubuntu dist={{ upstream.stdout }} bash
      become: true
      args:
        warn: no

    - name: add apt repositories
      apt_repository: repo={{ item }}
      become: true
      with_items:
        - ppa:numix/ppa
        - ppa:philip.scott/elementary-tweaks
        - ppa:jonathonf/vim

    - name: apt install
      apt: name={{ item }} update_cache=yes cache_valid_time=36
      become: true
      with_items:
        - apt-transport-https        # for docker
        - ca-certificates            # for docker
        - gnupg2                     # for docker
        - software-properties-common # for docker
        - docker-ce
        - gyazo
        - scrot # use from ~/.gyazo.config.yml
        - dconf-editor
        - gconf-editor
        - guake
        - git
        # - tig # need to install tig 2.4 manually
        - ranger
        - fcitx-mozc
        - byobu
        - jq
        - direnv
        - powertop
        - numix-icon-theme-circle
        - playonlinux
        - tlp
        - xclip
        - vim-gnome
        - synaptic
        - gdebi
        - xbindkeys
        - libinput-tools
        - elementary-tweaks
        - make
        - automake
        - autoconf
        - pkg-config
        - tree
        - sassc
        - gcc
        - snapd
        - gparted
        - python-pip
        - etckeeper
        - libreadline-dev
        - wmctrl
        - xdotool
        - gimp
        - inkscape
        - calibre
        - shellcheck
        - global
        - byzanz
        - baobab
        - fwupd
        - awscli
        - libmysqlclient-dev # for mysql2 gem
        - mysql-server
          # - vagrant # error occured by dependency of gems. Install from https://releases.hashicorp.com/vagrant/2.2.5/vagrant_2.2.5_linux_amd64.zip
        - virtualbox
        - virtualbox-ext-pack
        - tmate
        - libxcb-xtest0 # zoom dependency
    - name: snap install
      command: snap install {{ item }}
      become: true
      with_items:
        - bitwarden
        # - slack --classic # it doesn't works with fcitx
        - spotify
        - libreoffice
        - obs-studio
        - vlc
        - hub --classic
        - go --classic
        # - remmina # remmina can't read config on /home/ 
        # - ngrok   # ngrok   can't read config on /home/ 

    - name: pip install
      pip: name={{item}}
      with_items:
        - vint
        - wakatime

    - name: add $USER Docker group
      user: name=iberianpig groups=docker append=yes
      become: true

    - name: Download Terminal hybrid color schemes
      get_url:
        url: https://gist.github.com/iberianpig/95ba787d302c9cd5b0ef/raw/79e5d1272b9188d27ef15de9a53c66b3974ab600/hybrid-pantheon.sh
        dest: /tmp

    - name: set color schemes
      command: bash /tmp/hybrid-pantheon.sh

    - name: Install docker-compose # requrie 1.20 or later to use detachKeys in ~/.docker/config.json
      shell: |
        dest=/usr/local/bin/docker-compose
        version=$(curl --silent https://api.github.com/repos/docker/compose/releases/latest | jq .name -r)
        curl -L https://github.com/docker/compose/releases/download/$version/docker-compose-$(uname -s)-$(uname -m) -o $dest
        chmod a+x $dest
      args: 
        creates: /usr/local/bin/docker-compose
      become: true

    - name: Install Vagrant
      shell: |
        which vagrant || (curl -L https://releases.hashicorp.com/vagrant/2.2.5/vagrant_2.2.5_x86_64.deb -o /tmp/vagrant.deb && dpkg -i /tmp/vagrant.deb)
      become: true
      args:
        warn: no

    - name: Install Zoom
      shell: |
        which zoom || (curl -L https://zoom.us/client/latest/zoom_amd64.deb -o /tmp/zoom.deb && dpkg -i /tmp/zoom.deb)
      become: true
      args:
        warn: no

    - name: Install Fusuma
      command: gem install fusuma

    - name: add $USER Input group
      user: name=iberianpig groups=input append=yes
      become: true
